[package]
name = "ics-dm-azure-rs"
version = "0.1.0"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libics-dm-azure-sys = { path = "../libics-dm-azure-sys", features = ["build_sdk"] }
serde_json = "1.0"

