[package]
name = "ics-dm-azure-rs"
version = "0.1.0"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libics-dm-azure-sys = { git = "ssh://git@github.com/ICS-DeviceManagement/libics-dm-azure-sys.git", branch = "main" }
serde_json = "1.0"
log = "0.4"
